import Link from "next/link";
import { db } from "@/lib/supabase";
import type { Agent } from "@/lib/types";

export const dynamic = "force-dynamic";

export default async function AuditPage() {
  const [
    { data: agents },
    { data: guardEvent },
    { data: attackRun },
    { data: arrangementRecord },
  ] = await Promise.all([
    db().from("agents").select("*").is("archived_at", null).order("created_at"),
    db().from("call_events").select("call_id, payload").eq("type", "guard").order("id", { ascending: false }).limit(1).maybeSingle(),
    db().from("redteam_runs").select("call_id, persona").in("persona", ["fake_supervisor", "prompt_injector", "regulator_impostor"]).eq("passed", true).order("created_at", { ascending: false }).limit(1).maybeSingle(),
    db().from("arrangements").select("call_id, total, installments, offer_id").order("created_at", { ascending: false }).limit(1).maybeSingle(),
  ]);

  const collectionsAgent = ((agents as Agent[]) ?? []).find((a) => a.template === "collections") ?? agents?.[0];

  return (
    <>
      <div className="page-head">
        <div>
          <h1>Audit & Evaluation Guide</h1>
          <p className="muted">
            Evaluation reference for Lupitor reviewers: architectural invariants, test identities, and curated audit logs.
          </p>
        </div>
        {collectionsAgent && (
          <Link className="btn" href={`/agents/${collectionsAgent.id}/test`}>
            🎙️ Start test call
          </Link>
        )}
      </div>

      <div className="stack" style={{ gap: 24 }}>
        <div className="panel" style={{ borderLeft: "4px solid var(--ledger)" }}>
          <h2>Core Architectural Invariants</h2>
          <p className="muted">
            The platform design principle: <strong>the LLM talks, deterministic code decides</strong>.
          </p>
          <div className="grid-2" style={{ gap: 16, marginTop: 12 }}>
            <div style={{ background: "var(--paper)", padding: 14, borderRadius: "var(--radius-s)", border: "1px solid var(--rule)" }}>
              <strong>1. Settlement floor never reaches the LLM</strong>
              <p className="small muted" style={{ margin: "4px 0 0" }}>
                The floor is kept inside <code>OfferEngine</code>. It never appears in prompts, tool arguments, descriptions, or error messages.
              </p>
            </div>
            <div style={{ background: "var(--paper)", padding: 14, borderRadius: "var(--radius-s)", border: "1px solid var(--rule)" }}>
              <strong>2. Pre-TTS ResponseGuard</strong>
              <p className="small muted" style={{ margin: "4px 0 0" }}>
                Every sentence generated by the model passes through <code>ResponseGuard</code> before speech synthesis. Unapproved amounts or debt disclosures are blocked before spoken.
              </p>
            </div>
            <div style={{ background: "var(--paper)", padding: 14, borderRadius: "var(--radius-s)", border: "1px solid var(--rule)" }}>
              <strong>3. Commit by offer_id only</strong>
              <p className="small muted" style={{ margin: "4px 0 0" }}>
                The commitment tool accepts only engine-issued <code>offer_id</code>s. Callers cannot manipulate the bot into agreeing to unissued amounts.
              </p>
            </div>
            <div style={{ background: "var(--paper)", padding: 14, borderRadius: "var(--radius-s)", border: "1px solid var(--rule)" }}>
              <strong>4. Call Observance & Append-Only Audit</strong>
              <p className="small muted" style={{ margin: "4px 0 0" }}>
                Supervisors can listen live to any active call silently via WebRTC. Database tables for calls, events, and arrangements are append-only.
              </p>
            </div>
          </div>
        </div>

        <div className="grid-2">
          <div className="panel">
            <h2>Test Account (Dana Whitfield)</h2>
            <p className="small muted">
              Primary test identity used for phone dials and browser voice testing:
            </p>
            <dl className="facts" style={{ marginTop: 16 }}>
              <div><dt>Customer</dt><dd>Dana Whitfield</dd></div>
              <div><dt>Date of Birth</dt><dd>1988-03-14</dd></div>
              <div><dt>Billing ZIP</dt><dd>10027</dd></div>
              <div><dt>SSN Last 4</dt><dd>4417</dd></div>
              <div><dt>Current Balance</dt><dd>$4,120.60</dd></div>
              <div><dt>Portfolio</dt><dd>Prime (100 / 90 / 82 / 75%)</dd></div>
              <div><dt>Max concessions</dt><dd>2 per call</dd></div>
              <div><dt>Single-Call Floor</dt><dd>$3,378.89 (82%)</dd></div>
            </dl>
          </div>

          <div className="panel">
            <h2>Curated Audit Calls</h2>
            <p className="small muted">
              Direct links to inspect key safety behaviors recorded in real call timelines:
            </p>
            <div style={{ display: "grid", gap: 12, marginTop: 16 }}>
              <div style={{ padding: 12, background: "var(--paper)", borderRadius: "var(--radius-s)", border: "1px solid var(--rule)" }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                  <strong>🛡️ ResponseGuard in Action</strong>
                  {guardEvent?.call_id && (
                    <Link className="small" href={`/calls/${guardEvent.call_id}`}>Open call record →</Link>
                  )}
                </div>
                <p className="small muted" style={{ margin: "4px 0 0" }}>
                  Demonstrates real-time interception of unapproved amounts or disclosures with visual red audit stamps.
                </p>
              </div>

              <div style={{ padding: 12, background: "var(--paper)", borderRadius: "var(--radius-s)", border: "1px solid var(--rule)" }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                  <strong>🚫 Social Engineering Defeated</strong>
                  {attackRun?.call_id && (
                    <Link className="small" href={`/calls/${attackRun.call_id}`}>Open call record →</Link>
                  )}
                </div>
                <p className="small muted" style={{ margin: "4px 0 0" }}>
                  Fake supervisor override (Mark Ellison ID 55120) and prompt injection attempts firmly rejected.
                </p>
              </div>

              <div style={{ padding: 12, background: "var(--paper)", borderRadius: "var(--radius-s)", border: "1px solid var(--rule)" }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                  <strong>🤝 Compliant Settlement</strong>
                  {arrangementRecord?.call_id && (
                    <Link className="small" href={`/calls/${arrangementRecord.call_id}`}>Open call record →</Link>
                  )}
                </div>
                <p className="small muted" style={{ margin: "4px 0 0" }}>
                  Full negotiation lifecycle ending with legal read-back, schedule agreement, and commitment hash.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="panel">
          <h2>Testing Features</h2>
          <div className="grid-2" style={{ gap: 16, marginTop: 8 }}>
            <div>
              <h3>Call Observance (Live Listening)</h3>
              <p className="small muted">
                When a call is in progress, an <strong>🎧 Listen live</strong> button appears on the call record. Clicking it connects a silent supervisor WebRTC audio track to monitor live telephony or browser calls without alerting the participants.
              </p>
            </div>
            <div>
              <h3>Adversarial Red Team Harness</h3>
              <p className="small muted">
                View the <Link href="/redteam">Red team dashboard</Link> to inspect automated adversarial runs across 31 distinct caller personas testing jailbreaks, third-party disclosure, and settlement floors.
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
